# AWTRIX Matrix Display Automations for Glitch Cube

- id: awtrix_startup_display
  alias: "AWTRIX Startup Display"
  description: "Show startup message when system boots"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: "00:00:30"  # Wait for services to be ready
    - service: script.show_installation_message
      data:
        message: "Glitch Cube Online"
        icon_id: "52176"
        duration: 10
        color: "[0, 255, 100]"

- id: awtrix_environmental_updates
  alias: "AWTRIX Environmental Updates"
  description: "Periodically show environmental data"
  trigger:
    - platform: time_pattern
      minutes: "/15"  # Every 15 minutes
  condition:
    - condition: state
      entity_id: sensor.conversation_status
      state: "idle"
  action:
    - service: script.show_environmental_data

- id: awtrix_battery_monitoring
  alias: "AWTRIX Battery Monitoring"
  description: "Show battery level every hour or when it changes significantly"
  trigger:
    - platform: time_pattern
      minutes: 0  # Every hour
    - platform: state
      entity_id: sensor.battery_level
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: >
            {{ (trigger.to_state.state | int - trigger.from_state.state | int) | abs > 10 }}
        - condition: template
          value_template: "{{ trigger.platform == 'time_pattern' }}"
  action:
    - service: script.show_battery_level
      data:
        battery_level: "{{ states('sensor.battery_level') | int }}"
        charging: "{{ is_state('binary_sensor.charging', 'on') }}"

- id: awtrix_conversation_updates
  alias: "AWTRIX Conversation Status Updates"
  description: "Update display when conversation state changes"
  trigger:
    - platform: state
      entity_id: sensor.conversation_status
    - platform: state
      entity_id: sensor.visitor_count
  action:
    - service: script.show_conversation_status
      data:
        visitors: "{{ states('sensor.visitor_count') | int(0) }}"
        status: "{{ states('sensor.conversation_status') }}"

- id: awtrix_weather_morning
  alias: "AWTRIX Morning Weather"
  description: "Show weather information in the morning"
  trigger:
    - platform: time
      at: "08:00:00"
  action:
    - service: script.show_weather_info

- id: awtrix_special_events
  alias: "AWTRIX Special Event Notifications"
  description: "Show special messages for holidays or events"
  trigger:
    - platform: template
      value_template: >
        {{ 
          now().strftime('%m-%d') in ['01-01', '12-25', '07-04', '10-31'] or
          states('calendar.art_events') == 'on'
        }}
  action:
    - service: script.show_installation_message
      data:
        message: >
          {% set date = now().strftime('%m-%d') %}
          {% if date == '01-01' %}
            Happy New Year!
          {% elif date == '12-25' %}
            Merry Christmas!
          {% elif date == '07-04' %}
            Happy 4th of July!
          {% elif date == '10-31' %}
            Happy Halloween!
          {% else %}
            Art Event Today!
          {% endif %}
        icon_id: >
          {% set date = now().strftime('%m-%d') %}
          {% if date == '01-01' %}
            "32234"
          {% elif date == '12-25' %}
            "2064"
          {% elif date == '07-04' %}
            "15165"
          {% elif date == '10-31' %}
            "2116"
          {% else %}
            "8792"
          {% endif %}
        duration: 20
        color: "[255, 200, 0]"

- id: awtrix_error_notifications
  alias: "AWTRIX Error Notifications"
  description: "Display error messages when system issues occur"
  trigger:
    - platform: state
      entity_id: sensor.glitch_cube_app_health
      to: "unhealthy"
    - platform: state
      entity_id: sensor.internet_connectivity
      to: "offline"
  action:
    - service: script.show_installation_message
      data:
        message: >
          {% if trigger.entity_id == 'sensor.glitch_cube_app_health' %}
            System Error
          {% else %}
            No Internet
          {% endif %}
        icon_id: "23035"  # Warning icon
        duration: 30
        color: "[255, 50, 50]"

- id: awtrix_interaction_timeout
  alias: "AWTRIX Interaction Timeout Prompt"
  description: "Show prompts to encourage interaction after idle period"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_detected
      to: "on"
      for: "00:02:00"
  condition:
    - condition: state
      entity_id: sensor.conversation_status
      state: "idle"
  action:
    - service: script.show_interaction_prompt

- id: awtrix_daily_stats
  alias: "AWTRIX Daily Stats"
  description: "Show daily interaction statistics"
  trigger:
    - platform: time
      at: "20:00:00"  # 8 PM daily summary
  action:
    - service: script.show_installation_message
      data:
        message: "Today: {{ states('sensor.daily_interactions') | int(0) }} chats"
        icon_id: "52176"
        duration: 15
        color: "[100, 200, 255]"

- id: awtrix_maintenance_mode
  alias: "AWTRIX Maintenance Mode"
  description: "Show maintenance message when system is being updated"
  trigger:
    - platform: state
      entity_id: input_boolean.maintenance_mode
      to: "on"
  action:
    - service: script.awtrix_clear_all
    - service: script.show_installation_message
      data:
        message: "Maintenance Mode"
        icon_id: "23035"
        duration: 60
        color: "[255, 150, 0]"