generate_health_report:
  alias: "Generate Health Report"
  sequence:
    - service: homeassistant.update_entity
      target:
        entity_id:
          - sensor.glitch_cube_app_health
          - sensor.internet_connectivity
          - sensor.macmini_composite_temperature
          - sensor.macmini_uptime
          - sensor.installation_health
    - delay: "00:00:02"
    - service: logbook.log
      data:
        name: "Glitch Cube Health Report"
        message: >
          📊 Health Report {{ now().strftime('%Y-%m-%d %H:%M:%S') }} -
          Status: {{ states('sensor.current_status') }}
          App: {{ states('sensor.glitch_cube_app_health') }},
          Internet: {{ states('sensor.internet_connectivity') }},
          Temperature: {{ states('sensor.macmini_composite_temperature') }}°F,
          Uptime: {{ states('sensor.macmini_uptime') }},
          Offline Mode: {{ states('input_boolean.offline_mode') }}
        domain: "glitchcube"