---
# Manual SSH Key Setup Script
# This script can be manually triggered from the Home Assistant UI
# to set up SSH keys for git operations

setup_ssh_key:
  alias: "Setup SSH Key"
  description: "Manually configure SSH keys for git operations"
  icon: "mdi:key-variant"
  sequence:
    - service: shell_command.setup_ssh_key
      data: {}
    - delay:
        seconds: 5
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.ssh_key_status
    - service: persistent_notification.create
      data:
        title: "SSH Key Setup"
        message: >
          SSH key setup script executed.
          Current status: {{ states('sensor.ssh_key_health') }}
          
          Check the SSH Key Status sensor for details.
        notification_id: "ssh_key_setup_manual"
  mode: single

# Script to validate SSH key configuration
validate_ssh_key:
  alias: "Validate SSH Key"
  description: "Check SSH key status and configuration"
  icon: "mdi:key-check"
  sequence:
    - service: shell_command.check_ssh_key_status
      data: {}
    - delay:
        seconds: 2
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.ssh_key_status
    - service: persistent_notification.create
      data:
        title: "SSH Key Validation"
        message: >
          SSH key validation completed.
          Status: {{ states('sensor.ssh_key_health') }}
          
          {% set status = states('sensor.ssh_key_status') %}
          {% if status == 'configured' %}
          ✅ SSH key is properly configured and ready for git operations.
          {% elif status == 'invalid' %}
          ❌ SSH key exists but is invalid. Consider re-running setup.
          {% elif status == 'missing' %}
          ⚠️ SSH key not found. Run the Setup SSH Key script.
          {% else %}
          ❓ SSH key status could not be determined.
          {% endif %}
        notification_id: "ssh_key_validation"
  mode: single