inherit_from: .rubocop_todo.yml

# RuboCop configuration for Glitch Cube
# Art installation Ruby/Sinatra application

require:
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'data/**/*'
    - 'bin/**/*'
    - 'spec/fixtures/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style preferences for art installation context
Style/Documentation:
  Enabled: false  # Art installation - focus on functionality over docs

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false  # Allow compact namespace definitions


Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'app.rb'
    - lib/services/beacon_service.rb

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'app.rb'
    - 'Rakefile'
    - 'db/migrations/**/*'
    - 'db/schema.rb'
    - 'deprecated/**/*'
    - 'discover_tts_voices.rb'
    - 'lib/routes/**/*'
    - 'lib/services/gps_tracking_service.rb'
    - 'lib/tasks/**/*'

Metrics/ModuleLength:
  Max: 150

# Security
Security/Eval:
  Enabled: true

# RSpec specific rules - relaxed for art installation testing
RSpec/ExampleLength:
  Max: 30  # Allow longer examples for integration tests

RSpec/MultipleExpectations:
  Max: 15  # Allow more expectations in integration tests

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false  # Integration tests don't always describe classes

# Disable overly strict RSpec rules for art installation
RSpec/AnyInstance:
  Enabled: false  # Allow any_instance_of for mocking in art installation

RSpec/MessageSpies:
  Enabled: false  # Allow traditional stubbing patterns

RSpec/VerifiedDoubles:
  Enabled: false  # Allow simple doubles for testing

RSpec/PendingWithoutReason:
  Enabled: false  # Allow pending tests without detailed reasons

RSpec/ContextWording:
  Enabled: false  # Allow flexible context descriptions

# Disable problematic cops for art installation
Lint/MissingSuper:
  Enabled: false  # Art installation framework may not require super calls

Style/GlobalVars:
  Enabled: false  # May need globals for art installation state

Style/ClassVars:
  Enabled: false  # May need class variables for shared state

# Disable RSpec linting cops that are too strict
RSpec/StubbedMock:
  Enabled: false  # Allow expect for stubbing in tests

RSpec/SpecFilePathFormat:
  Enabled: false  # Allow flexible spec file naming