version: '3.8'

services:
  # Helicone AI Gateway for observability
  helicone-gateway:
    container_name: glitchcube_helicone_gateway
    image: helicone/ai-gateway:main
    ports:
      - "8080:8080"
    environment:
      - AI_GATEWAY__SERVER__ADDRESS=0.0.0.0  # Required for Docker
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - HELICONE_API_KEY=${HELICONE_API_KEY:-}  # Optional, for observability
    volumes:
      - ./ai-gateway-config.yaml:/helicone-config/config.yaml  # Optional custom config
    command: ["ai-gateway", "-c", "/helicone-config/config.yaml"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Home Assistant container
  homeassistant:
    container_name: glitchcube_homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file: .env  # Pull TZ from .env file
    deploy:
      resources:
        limits:
          cpus: '1.5'   # 1.5 CPU cores for HA
          memory: 3G    # 3GB RAM for HA

  # Glitch Cube Sinatra application
  glitchcube:
    container_name: glitchcube_app
    build: .
    image: glitchcube:latest
    volumes:
      - glitchcube_data:/app/data
      - glitchcube_context:/app/data/context_documents
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4567:4567"
    restart: unless-stopped
    env_file: .env  # Pull all vars from .env file
    environment:
      # Override specific vars for Docker networking
      - REDIS_URL=redis://redis:6379/0
      - HA_URL=http://host.docker.internal:8123
      - AI_GATEWAY_URL=http://helicone-gateway:8080
    depends_on:
      - homeassistant
      - redis
      - helicone-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/health", "||", "exit", "1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '0.75'   # 0.75 CPU cores for Sinatra
          memory: 1G     # 1GB RAM for Sinatra

  # Redis for Sidekiq background jobs
  redis:
    container_name: glitchcube_redis
    image: redis:7-alpine
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'   # 0.25 CPU cores for Redis
          memory: 256M   # 256MB RAM for Redis

  # Sidekiq worker (separate container for background jobs)
  sidekiq:
    container_name: glitchcube_sidekiq
    build: .
    image: glitchcube:latest
    command: bundle exec sidekiq -r ./app.rb
    volumes:
      - glitchcube_data:/app/data
      - glitchcube_context:/app/data/context_documents
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    env_file: .env  # Pull all vars from .env file
    environment:
      # Override specific vars for Docker networking
      - REDIS_URL=redis://redis:6379/0
      - HA_URL=http://host.docker.internal:8123
      - AI_GATEWAY_URL=http://helicone-gateway:8080
    depends_on:
      - redis
      - homeassistant
      - helicone-gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'    # 0.5 CPU cores for Sidekiq
          memory: 512M   # 512MB RAM for Sidekiq

  # Portainer for Docker management UI
  portainer:
    container_name: glitchcube_portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"  # HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file: .env
    environment:
      - PORTAINER_ADMIN_PASSWORD=${MASTER_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    profiles:
      - management  # Optional: only start when --profile management is used

  # MQTT Broker for device communication
  mosquitto:
    container_name: glitchcube_mosquitto
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # ESPHome for custom hardware integration
  esphome:
    container_name: glitchcube_esphome
    image: esphome/esphome:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6052/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Music Assistant for audio playback
  music-assistant:
    container_name: glitchcube_music_assistant
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/music-assistant:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-America/Los_Angeles}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G  

  # Glances for system monitoring
  glances:
    container_name: glitchcube_glances
    image: nicolargo/glances:latest
    restart: unless-stopped
    privileged: true
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - GLANCES_OPT=-w --time 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:61208/api/3/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Log viewer for monitoring all container logs
  dozzle:
    container_name: glitchcube_logviewer
    image: amir20/dozzle:latest
    restart: unless-stopped
    ports:
      - "8888:8080"  # Web UI on port 8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="name=glitchcube_*"  # Only show Glitch Cube containers
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/logs"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # File Editor (exact equivalent of HA File Editor addon)
  file-editor:
    container_name: glitchcube_file_editor
    image: causticlab/hass-configurator-docker:latest
    restart: unless-stopped
    ports:
      - "3218:3218"  # File editor on port 3218
    volumes:
      - homeassistant_config:/config  # HA config directory
      - .:/app  # Project directory for editing glitchcube files
      - ./data/configurator:/configurator_config  # Configurator settings
    environment:
      - HC_BASEPATH=/config
      - HC_ENFORCE_BASEPATH=true
      - HC_USERNAME=${MASTER_PASSWORD:-admin}
      - HC_PASSWORD=${MASTER_PASSWORD:-glitchcube}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3218/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  homeassistant_config:
    driver: local
  glitchcube_data:
    driver: local
  glitchcube_context:
    driver: local
  redis_data:
    driver: local
  portainer_data:
    driver: local
  code_server_data:
    driver: local