name: Deploy to Mac mini (VM + Host)

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Trigger Home Assistant VM deployment
      env:
        HA_WEBHOOK_URL: ${{ secrets.HA_WEBHOOK_URL }}
      run: |
        echo "🏠 Triggering Home Assistant VM deployment..."
        
        # Send webhook to Home Assistant
        # HA will pull from GitHub and update its config
        curl -X POST "$HA_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "ref": "refs/heads/main",
            "after": "${{ github.sha }}",
            "repository": {
              "full_name": "${{ github.repository }}"
            }
          }' \
          --fail \
          --show-error \
          || echo "⚠️  Failed to trigger HA deployment (may be updating already)"
    
    - name: Trigger Sinatra host deployment
      env:
        SINATRA_DEPLOY_URL: ${{ secrets.SINATRA_DEPLOY_URL }}
        GITHUB_WEBHOOK_SECRET: ${{ secrets.GITHUB_WEBHOOK_SECRET }}
      run: |
        echo "🚀 Triggering Sinatra host deployment..."
        
        # Create the payload
        PAYLOAD='{
          "ref": "refs/heads/main",
          "after": "${{ github.sha }}",
          "repository": {
            "full_name": "${{ github.repository }}"
          }
        }'
        
        # Calculate signature (if webhook secret is set)
        if [ -n "$GITHUB_WEBHOOK_SECRET" ]; then
          SIGNATURE="sha256=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$GITHUB_WEBHOOK_SECRET" | cut -d' ' -f2)"
          
          curl -X POST "$SINATRA_DEPLOY_URL" \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: $SIGNATURE" \
            -d "$PAYLOAD" \
            --fail \
            --show-error \
            || echo "⚠️  Failed to trigger Sinatra deployment"
        else
          # No signature verification
          curl -X POST "$SINATRA_DEPLOY_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            --fail \
            --show-error \
            || echo "⚠️  Failed to trigger Sinatra deployment"
        fi
    
    - name: Wait for deployments
      run: |
        echo "⏳ Waiting 30 seconds for deployments to complete..."
        sleep 30
        echo "✅ Deployment triggers completed!"