---
# SSH Key Status Sensors
# Monitor SSH key configuration and status for git operations

# Command sensor to check SSH key status
- platform: command_line
  name: "SSH Key Status"
  command: |
    if [ -f "/root/.ssh/id_rsa" ]; then
      if ssh-keygen -l -f /root/.ssh/id_rsa >/dev/null 2>&1; then
        echo "configured"
      else
        echo "invalid"
      fi
    else
      echo "missing"
    fi
  scan_interval: 3600  # Check every hour
  value_template: "{{ value }}"

# Template sensor for human-readable SSH key status
- platform: template
  sensors:
    ssh_key_health:
      friendly_name: "SSH Key Health"
      value_template: >
        {% set status = states('sensor.ssh_key_status') %}
        {% if status == 'configured' %}
          Configured ✅
        {% elif status == 'invalid' %}
          Invalid ❌
        {% elif status == 'missing' %}
          Missing ⚠️
        {% else %}
          Unknown ❓
        {% endif %}
      icon_template: >
        {% set status = states('sensor.ssh_key_status') %}
        {% if status == 'configured' %}
          mdi:key-variant
        {% elif status == 'invalid' %}
          mdi:key-remove
        {% elif status == 'missing' %}
          mdi:key-alert
        {% else %}
          mdi:key-question
        {% endif %}
      attribute_templates:
        status: "{{ states('sensor.ssh_key_status') }}"
        last_checked: "{{ states.sensor.ssh_key_status.last_updated }}"
        description: >
          {% set status = states('sensor.ssh_key_status') %}
          {% if status == 'configured' %}
            SSH key is properly configured and valid
          {% elif status == 'invalid' %}
            SSH key exists but is invalid or corrupted
          {% elif status == 'missing' %}
            SSH key not found - run SSH key setup automation
          {% else %}
            SSH key status could not be determined
          {% endif %}