conversation_state:
  name: Conversation State
  initial: idle
  max: 32

last_error:
  name: Last Error
  initial: none
  max: 255

current_track:
  name: Current Track
  initial: "No music playing"
  max: 128