---
# Input Text helpers for Glitch Cube
current_persona:
  name: "Current AI Persona"
  max: 100
  initial: "Default"
  
current_environment:
  name: "Current Environment"
  max: 255
  initial: "Unknown location"
  icon: "mdi:map-marker-radius"
  
current_weather:
  name: "Current Weather Summary"
  max: 255
  initial: "Weather data unavailable"
  icon: "mdi:weather-partly-cloudy"

glitchcube_host:
  name: "Glitch Cube Host IP"
  max: 15
  icon: "mdi:cube-outline"

camera_vision_analysis:
  name: "Camera Vision Analysis"
  max: 255
  initial: "No analysis available"
  icon: "mdi:camera-iris"