---
homeassistant:
  name: "Glitch Cube"
  latitude: 40.7682435937
  longitude: -119.218725792
  elevation: 3848
  time_zone: "America/Los_Angeles"

  
  # Allow external webhooks for art installation
  external_url: "https://zjd6lgd6yhigawnj06mkguhholcsfdul.ui.nabu.casa:8123"
  internal_url: "http://localhost:8123"

# Enable frontend and API
frontend:
  themes: !include_dir_merge_named themes

# Enable configuration panel
config:

# Enable logbook for tracking interactions
logbook:
  # Note: include/exclude options are deprecated, use entity/automation filters instead

# Enable history tracking
history:
  # Note: include/exclude options are deprecated, use entity filters instead

# Enable recorder with optimized settings for art installation
recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_keep_days: 10  # Keep 30 days of history
  commit_interval: 5   # Commit every 5 seconds for reliability
  include:
    domains:
      - sensor
      - automation
      - input_datetime
      - input_text
      - logbook
    entities:
      - sensor.glitch_cube_app_health
      - sensor.internet_connectivity
      - sensor.installation_health
      - sensor.last_interaction_time
      - sensor.current_persona

# HTTP configuration for webhooks
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 10.0.0.0/8

# Network discovery (removed - deprecated in modern HA)
# discovery:

# Enable mobile app support
mobile_app:

# Enable system health
system_health:

# Enable diagnostics
diagnostics:

# Include separate configuration files
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/

# Include all input helpers (each type from separate files)
input_datetime: !include input_helpers/input_datetime.yaml
input_text: !include input_helpers/input_text.yaml
input_number: !include input_helpers/input_number.yaml
input_boolean: !include input_helpers/input_boolean.yaml

# Include all sensors (REST sensors and template sensors)
sensor: !include_dir_merge_list sensors/
template: !include_dir_merge_list template/

# Enable webhook integration (for external API calls)
webhook:

# Enable RESTful API
api:

# REST Commands for external integrations
rest_command:
  # Update external status page (Uptime Kuma)
  update_status_page:
    url: "https://status.wlux.casa/api/push/Bf8nrx6ykq?status={{ status }}&msg={{ msg | urlencode }}&ping={{ ping }}"
    method: GET
    headers:
      User-Agent: "Glitch Cube Status Monitor"
    timeout: 10

# Shell commands for deployment
shell_command:
  deploy_glitchcube: '/home/eric/glitchcube/scripts/pull-from-github.sh'
  rollback_glitchcube: 'cd /home/eric/glitchcube && docker tag glitchcube:last-known-good glitchcube:latest && docker-compose up -d glitchcube sidekiq'

# Scene configuration for different installation modes
scene: !include scenes.yaml

# Logger configuration with verbose logging for important components
logger:
  default: info  # More verbose default level
  logs:
    # Suppress all Python warnings (deprecation, import, version mismatches, etc.)
    py.warnings: error
    # Suppress custom integration warnings
    homeassistant.loader: error
    
    # Verbose logging for key components
    homeassistant.core: info
    homeassistant.components.webhook: info
    homeassistant.components.rest: info
    homeassistant.components.sensor: info
    homeassistant.components.automation: info
    homeassistant.components.script: info
    homeassistant.helpers.template: info
    
    # Integration and config flow logging
    homeassistant.config_entries: info
    homeassistant.data_entry_flow: info
    homeassistant.setup: info
    homeassistant.bootstrap: info
    homeassistant.components.integration: info
    
    # Keep authentication warnings visible
    homeassistant.components.http.ban: warning
    homeassistant.components.auth: info

# Note: panel_iframe has been deprecated in newer HA versions
# Use the Home Assistant Community Store (HACS) integrations for file editing
# or access services directly via their URLs:
# - File Editor: http://glitchcube.local:3218
# - Log Viewer: http://glitchcube.local:8888