# MQTT Configuration for Glitch Cube integrations
mqtt:
  broker: localhost
  port: 1883
  username: !env_var MQTT_USERNAME "glitchcube"
  password: !env_var MQTT_PASSWORD "glitchcube123"
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "homeassistant/status"
    payload: "online"
  will_message:
    topic: "homeassistant/status"
    payload: "offline"

# Govee devices will auto-discover via MQTT discovery
# AWTRIX devices will be added manually or via custom component