# REST commands for GitHub deployment automation
rest_command:
  trigger_glitchcube_deployment:
    url: "{{ states('input_text.glitchcube_host_url') }}/api/v1/deploy/internal"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "repository": "{{ repository }}",
        "branch": "{{ branch }}",
        "commit_sha": "{{ commit_sha }}",
        "commit_message": "{{ commit_message }}",
        "committer": "{{ committer }}",
        "timestamp": "{{ now().isoformat() }}"
      }
    timeout: 60
    
  check_deployment_status:
    url: "{{ states('input_text.glitchcube_host_url') }}/api/v1/deploy/status"
    method: GET
    timeout: 10
    
  manual_glitchcube_deployment:
    url: "{{ states('input_text.glitchcube_host_url') }}/api/v1/deploy/internal"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "repository": "manual deployment",
        "branch": "main",
        "commit_sha": "manual",
        "commit_message": "{{ message | default('Manual deployment from Home Assistant') }}",
        "committer": "{{ committer | default('Home Assistant') }}",
        "timestamp": "{{ now().isoformat() }}"
      }
    timeout: 60