# Glitch Cube Health and Status Sensors
# These sensors monitor the art installation's health and state

# Health Sensors
sensor:
  # Sinatra App Health (REST sensor checking our /health endpoint)
  - platform: rest
    resource: "http://glitchcube.local:4567/health"
    name: "Glitch Cube App Health"
    unique_id: "glitchcube_app_health"
    scan_interval: 30  # Check every 30 seconds
    timeout: 10
    headers:
      User-Agent: "Home Assistant Health Check"
    value_template: >
      {% if value_json is defined and value_json.status == "ok" %}
        online
      {% else %}
        offline
      {% endif %}
    json_attributes:
      - version
      - uptime
      - redis_status
      - database_status
    icon: "mdi:cube-outline"
    
  # Internet Connectivity Health
  - platform: rest
    resource: "http://httpbin.org/get"
    name: "Internet Connectivity"
    unique_id: "internet_connectivity"
    scan_interval: 60  # Check every minute
    timeout: 15
    value_template: >
      {% if value_json is defined %}
        connected
      {% else %}
        disconnected
      {% endif %}
    icon: "mdi:web"
    
  # Note: Using Glances sensors instead:
  # - sensor.cube_cpu_thermal_0_temperature (Fahrenheit)
  # - sensor.cube_uptime

# Template Sensors for Dynamic State Management
template:
  - sensor:
      # Last Interaction Time (updated via webhook)
      - name: "Last Interaction Time"
        unique_id: "last_interaction_time"
        state: "{{ states('input_datetime.last_interaction') | as_timestamp | timestamp_custom('%Y-%m-%d %H:%M:%S') if states('input_datetime.last_interaction') != 'unknown' else 'Never' }}"
        icon: "mdi:clock-outline"
        
      # Current Persona (updated via webhook)
      - name: "Current Persona"
        unique_id: "current_persona"
        state: "{{ states('input_text.current_persona') if states('input_text.current_persona') != 'unknown' else 'Default' }}"
        icon: "mdi:account-multiple"
        
      # Installation Health Summary
      - name: "Installation Health"
        unique_id: "installation_health"
        state: >
          {% set app_health = states('sensor.glitch_cube_app_health') %}
          {% set internet = states('sensor.internet_connectivity') %}
          {% set temp = states('sensor.cube_cpu_thermal_0_temperature') | float(0) %}
          {% set offline_mode = states('input_boolean.offline_mode') %}
          
          {% if app_health == 'offline' %}
            critical
          {% elif internet == 'disconnected' and offline_mode == 'on' %}
            offline
          {% elif internet == 'disconnected' %}
            degraded
          {% elif temp > 158 %}
            warning
          {% else %}
            healthy
          {% endif %}
        icon: >
          {% set health = states('sensor.installation_health') %}
          {% if health == 'critical' %}
            mdi:alert-circle
          {% elif health == 'offline' %}
            mdi:wifi-off
          {% elif health == 'degraded' %}
            mdi:alert
          {% elif health == 'warning' %}
            mdi:alert-outline
          {% else %}
            mdi:check-circle
          {% endif %}

# Input helpers for storing updatable state
input_datetime:
  last_interaction:
    name: "Last Interaction Timestamp"
    has_date: true
    has_time: true
    
input_text:
  current_persona:
    name: "Current AI Persona"
    max: 100
    initial: "Default"
    
  current_environment:
    name: "Current Environment"
    max: 255
    initial: "Unknown location"
    icon: "mdi:map-marker-radius"
    
  current_weather:
    name: "Current Weather Summary"
    max: 255
    initial: "Weather data unavailable"
    icon: "mdi:weather-partly-cloudy"

input_number:
  avg_sound_db:
    name: "Average Sound Level"
    min: 0
    max: 120
    step: 0.1
    unit_of_measurement: "dB"
    initial: 40.0
    icon: "mdi:volume-high"

input_boolean:
  offline_mode:
    name: "Offline Mode"
    initial: false
    icon: "mdi:wifi-off"
    
  # Human Interaction Sensors
  motion_detected:
    name: "Motion Detected"
    initial: false
    icon: "mdi:motion-sensor"
    
  human_detected:
    name: "Human Detected"
    initial: false
    icon: "mdi:account-search"
    
  # Movement & Position Sensors
  cube_is_moving:
    name: "Cube Is Moving"
    initial: false
    icon: "mdi:cube-scan"
    
  cube_stopped_moving:
    name: "Cube Stopped Moving"
    initial: false
    icon: "mdi:cube-outline"
    
  cube_tilted:
    name: "Cube Tilted"
    initial: false
    icon: "mdi:rotate-3d-variant"
    
  cube_stable:
    name: "Cube Stable"
    initial: true
    icon: "mdi:cube"
    
  # System Health Sensors
  battery_low:
    name: "Battery Low"
    initial: false
    icon: "mdi:battery-low"
    
  resources_low:
    name: "Resources Low"
    initial: false
    icon: "mdi:memory"
    
  temp_critical:
    name: "Temperature Critical"
    initial: false
    icon: "mdi:thermometer-alert"