# Home Assistant automation to trigger deployment via webhook
# Add this to your Home Assistant automations

automation:
  - alias: "GitHub Deploy Trigger"
    description: "Trigger deployment when GitHub webhook is received"
    trigger:
      - platform: webhook
        webhook_id: github_deploy_trigger
        allowed_methods:
          - POST
    condition:
      - condition: template
        value_template: "{{ trigger.json.ref == 'refs/heads/main' }}"
    action:
      - service: shell_command.deploy_glitchcube
      - service: notify.persistent_notification
        data:
          title: "Glitch Cube Deployment"
          message: "Deployment triggered for commit: {{ trigger.json.after[:7] }}"

# Add this shell command to configuration.yaml
shell_command:
  deploy_glitchcube: '/home/eric/glitchcube/scripts/auto-deploy.sh'
  
# Input boolean to track deployment status
input_boolean:
  glitchcube_deploying:
    name: Glitch Cube Deploying
    initial: off
    
# Sensor to track last deployment
input_text:
  last_deployment_commit:
    name: Last Deployment Commit
    initial: "none"
    max: 40