simulate_cube_movement_worker:
  cron: "*/5 * * * *" # Every 5 minutes (will update every 30 seconds internally)
  class: "Jobs::SimulateCubeMovementWorker"
  queue: default
  description: "Simulate Glitch Cube GPS movement for testing (set SIMULATE_CUBE_MOVEMENT=true to activate)"
# The following jobs still use Sidekiq-cron until migrated to Desiru scheduler:

memory_cleanup:
  cron: "0 */6 * * *"  # Every 6 hours
  class: "Jobs::MemoryCleanupJob"
  queue: low
  description: "Clean up old memory files and consolidate data"

host_registration:
  cron: "*/5 * * * *"  # Every 5 minutes
  class: "HostRegistrationWorker"
  queue: default
  description: "Register Glitch Cube IP with Home Assistant for dynamic discovery"