# Input helpers for conversation state tracking and debug mode

input_text:
  # Current conversation state (set by Sinatra API)
  conversation_state:
    name: Conversation State
    initial: idle
    max: 32
    
  # Last error message for debugging
  last_error:
    name: Last Error
    initial: none
    max: 255

  # Current track info for music display
  current_track:
    name: Current Track
    initial: "No music playing"
    max: 128

input_boolean:
  # Debug mode toggle for additional dashboard info
  debug_mode:
    name: Debug Mode
    initial: false
    icon: mdi:bug

  # Conversation recording mode
  record_conversations:
    name: Record Conversations
    initial: true
    icon: mdi:record-rec

input_number:
  # Memory usage tracking
  memory_usage:
    name: Memory Usage
    initial: 0
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:memory

  # CPU usage tracking  
  cpu_usage:
    name: CPU Usage
    initial: 0
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:chip