memory_usage:
  name: Memory Usage
  initial: 0
  min: 0
  max: 100
  unit_of_measurement: "%"
  icon: mdi:memory

cpu_usage:
  name: CPU Usage
  initial: 0
  min: 0
  max: 100
  unit_of_measurement: "%"
  icon: mdi:chip