last_deployment_time:
  name: Last Deployment Time
  initial: "Never"
  max: 50
  icon: mdi:clock-outline

last_deployment_commit:
  name: Last Deployment Commit
  initial: "unknown"
  max: 40
  icon: mdi:git