# Input Number helpers for Glitch Cube
avg_sound_db:
  name: "Average Sound Level"
  min: 0
  max: 120
  step: 0.1
  unit_of_measurement: "dB"
  initial: 40.0
  icon: "mdi:volume-high"

# Storage for daily distance (persists between restarts)
glitch_cube_daily_distance_storage:
  name: "Daily Distance Storage"
  min: 0
  max: 1000
  step: 0.01
  unit_of_measurement: "km"
  icon: mdi:map-marker-distance

# Storage for total distance (persists between restarts)
glitch_cube_total_distance_storage:
  name: "Total Distance Storage"
  min: 0
  max: 10000
  step: 0.01
  unit_of_measurement: "km"
  icon: mdi:counter

# Store previous GPS coordinates for movement detection
glitch_cube_prev_lat:
  name: "Previous Latitude"
  min: -90
  max: 90
  step: 0.000001
  unit_of_measurement: "°"
  icon: mdi:map-marker

glitch_cube_prev_lng:
  name: "Previous Longitude" 
  min: -180
  max: 180
  step: 0.000001
  unit_of_measurement: "°"
  icon: mdi:map-marker