# Input helpers for auto-recovery system

input_boolean:
  # Manual triggers
  trigger_restart:
    name: "Trigger Manual Restart"
    icon: mdi:restart
    
  maintenance_mode:
    name: "Maintenance Mode"
    icon: mdi:wrench
    initial: false
    
  auto_recovery_enabled:
    name: "Auto Recovery Enabled"
    icon: mdi:shield-check
    initial: true

input_select:
  restart_level:
    name: "Restart Level"
    options:
      - soft
      - hard
      - nuclear
    initial: soft
    icon: mdi:gauge

input_datetime:
  last_restart_time:
    name: "Last Restart Time"
    has_date: true
    has_time: true
    icon: mdi:history

input_text:
  restart_auth_token:
    name: "Restart Auth Token"
    mode: password
    icon: mdi:key
    initial: "change-me-in-production"
    
  glitchcube_host_url:
    name: "Glitch Cube Host URL"
    icon: mdi:web
    initial: "http://speedygonzo.local:4567"

input_number:
  restart_threshold:
    name: "Consecutive Failures Before Restart"
    min: 1
    max: 10
    step: 1
    initial: 3
    icon: mdi:counter
    
  restart_cooldown_minutes:
    name: "Minimum Minutes Between Restarts"
    min: 5
    max: 60
    step: 5
    initial: 10
    icon: mdi:timer-sand