trigger_restart:
  name: "Trigger Manual Restart"
  icon: mdi:restart

maintenance_mode:
  name: "Maintenance Mode"
  icon: mdi:wrench
  initial: false

auto_recovery_enabled:
  name: "Auto Recovery Enabled"
  icon: mdi:shield-check
  initial: true