---
http_interactions:
- request:
    method: post
    uri: http://glitch.local:8123/api/services/event/fire
    body:
      encoding: UTF-8
      base64_string: |
        eyJldmVudF90eXBlIjoidGVzdF93YWtlX3dvcmQiLCJldmVudF9kYXRhIjp7
        Im1lc3NhZ2UiOiJIZWxsbyBmcm9tIHNpbXVsYXRlZCB3YWtlIHdvcmQifX0=
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - glitch.local:8123
      Authorization:
      - Bearer <TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Referrer-Policy:
      - no-referrer
      X-Content-Type-Options:
      - nosniff
      Server:
      - ''
      X-Frame-Options:
      - SAMEORIGIN
      Content-Length:
      - '17'
      Date:
      - Sat, 09 Aug 2025 00:25:03 GMT
    body:
      encoding: UTF-8
      base64_string: 'NDAxOiBVbmF1dGhvcml6ZWQ=

        '
  recorded_at: Sat, 09 Aug 2025 00:25:03 GMT
recorded_with: VCR 6.3.1
