#!/usr/bin/env ruby
# frozen_string_literal: true

# Home Assistant Service Schema Sync Utility
#
# This script analyzes our tool schemas against Home Assistant's actual service definitions
# and provides recommendations for keeping them in sync.
#
# Usage:
#   ruby scripts/ha_schema_sync.rb                    # Analyze all tools
#   ruby scripts/ha_schema_sync.rb --tool LightingTool # Analyze specific tool
#   ruby scripts/ha_schema_sync.rb --check-ha         # Check HA connectivity and list services

require_relative '../config/environment'

# Ensure all required classes are loaded
require_relative '../lib/core/home_assistant_client'
require_relative '../lib/services/system/ha_service_validator'

class HASchemaSync
  def initialize
    @ha_client = HomeAssistantClient.new
    @validator = Services::HAServiceValidator
  end

  def run(options = {})
    if options[:check_ha]
      check_ha_connectivity
      return
    end

    tool_classes = if options[:tool]
                     [Object.const_get(options[:tool])]
                   else
                     Services::ToolRegistryService::ALL_TOOL_CLASSES
                   end

    puts '🔍 Analyzing tool schemas and generating documentation...'
    puts '=' * 60

    # Generate markdown documentation
    output_file = options[:output] || 'docs/home_assistant_service_schemas.md'
    markdown_content = generate_markdown_documentation(tool_classes)

    File.write(output_file, markdown_content)
    puts "📝 Generated documentation: #{output_file}"

    # Also output to console for immediate review
    puts "\nConsole Analysis:"
    puts '=' * 40
    tool_classes.each do |tool_class|
      analyze_tool_class(tool_class)
      puts
    end

    puts 'Analysis complete! 🎉'
  end

  private

  def generate_markdown_documentation(tool_classes)
    content = []
    content << '# Home Assistant Service Schema Reference'
    content << ''
    content << 'This document maps our GlitchCube tool methods to their corresponding Home Assistant services'
    content << 'and provides detailed parameter information for LLM context.'
    content << ''
    content << "_Auto-generated by `scripts/ha_schema_sync.rb` on #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}_"
    content << ''

    tool_classes.each do |tool_class|
      class_content = generate_tool_class_documentation(tool_class)
      content.concat(class_content) if class_content.any?
    end

    content.join("\n")
  end

  def generate_tool_class_documentation(tool_class)
    class_name = tool_class.name.split('::').last
    return [] unless tool_class.respond_to?(:available_tools)

    content = []
    content << "## #{class_name}"
    content << ''

    if tool_class.respond_to?(:prompt_description)
      content << "**Description:** #{tool_class.prompt_description}"
      content << ''
    end

    tool_class.available_tools.each do |tool_method|
      method_content = generate_method_documentation(tool_class, tool_method)
      content.concat(method_content)
    end

    content << ''
    content
  end

  def generate_method_documentation(tool_class, tool_method)
    content = []
    content << "### `#{tool_method}`"
    content << ''

    # Get tool schema
    tool_schema = tool_class.respond_to?(:tool_schemas) ? tool_class.tool_schemas[tool_method] : nil

    if tool_schema
      content << '**Tool Schema Parameters:**'
      content << ''
      tool_properties = tool_schema['properties'] || {}
      required_fields = tool_schema['required'] || []

      tool_properties.each do |param, config|
        required_marker = required_fields.include?(param) ? ' *(required)*' : ''
        param_type = config['type'] || 'any'
        description = config['description'] || ''

        content << "- `#{param}` (#{param_type})#{required_marker}"
        content << "  #{description}" if description.length.positive?

        # Show enums
        if config['enum']
          content << "  - Allowed values: #{config['enum'].join(', ')}"
        end

        # Show ranges
        next unless config['minimum'] || config['maximum']

        range_info = []
        range_info << "min: #{config['minimum']}" if config['minimum']
        range_info << "max: #{config['maximum']}" if config['maximum']
        content << "  - Range: #{range_info.join(', ')}"
      end
      content << ''
    end

    # Get HA service mappings
    comparison = @validator.compare_tool_schema_to_ha(tool_class, tool_method)

    if comparison[:status] == :compared && comparison[:comparisons].any?
      content << '**Home Assistant Service Mappings:**'
      content << ''

      comparison[:comparisons].each do |comp|
        ha_content = generate_ha_service_documentation(comp)
        content.concat(ha_content)
      end
    else
      content << '_No Home Assistant service mappings detected for this method._'
      content << ''
    end

    content << '---'
    content << ''
    content
  end

  def generate_ha_service_documentation(comp)
    content = []
    service_name = "#{comp[:domain]}.#{comp[:service]}"

    content << "#### HA Service: `#{service_name}`"
    content << ''

    if comp[:status] == :ha_schema_unavailable
      content << '_Schema unavailable_'
      content << ''
      return content
    end

    ha_schema = comp[:ha_schema]
    if ha_schema[:description]
      content << "**Description:** #{ha_schema[:description]}"
      content << ''
    end

    fields = ha_schema[:fields] || {}
    if fields.any?
      content << '**Expected Parameters:**'
      content << ''

      fields.each do |field_name, field_info|
        required_marker = field_info['required'] ? ' *(required)*' : ''
        description = field_info['description'] || 'No description'

        content << "- `#{field_name}`#{required_marker}: #{description}"

        # Add selector type information
        selector = field_info['selector']
        next unless selector&.any?

        selector_type = selector.keys.first
        selector_config = selector.values.first

        content << "  - Type: #{selector_type}"

        case selector_type
        when 'select'
          options = selector_config&.dig('options')
          content << "  - Options: #{options.join(', ')}" if options
        when 'number'
          min_val = selector_config&.dig('min')
          max_val = selector_config&.dig('max')
          range_parts = []
          range_parts << "min: #{min_val}" if min_val
          range_parts << "max: #{max_val}" if max_val
          content << "  - Range: #{range_parts.join(', ')}" if range_parts.any?
        when 'text'
          multiline = selector_config&.dig('multiline')
          content << "  - Multiline: #{multiline}" if multiline
        end
      end
      content << ''
    end

    # Add compatibility notes
    case comp[:status]
    when :compatible
      content << '✅ **Compatibility:** Tool schema is compatible with HA service'
    when :mismatched
      content << '⚠️ **Compatibility Issues:**'
      comp[:mismatches].each do |mismatch|
        content << "- #{mismatch}"
      end
    end

    if comp[:suggestions]&.any?
      content << ''
      content << '💡 **Suggestions:**'
      comp[:suggestions].each do |suggestion|
        content << "- #{suggestion}"
      end
    end

    content << ''
    content
  end

  def check_ha_connectivity
    puts '🏠 Checking Home Assistant connectivity...'
    puts "URL: #{@ha_client.base_url}"

    begin
      services = @ha_client.get_services
      puts '✅ Connected successfully!'
      puts "📋 Available service domains: #{services.keys.sort.join(', ')}"

      # Show services for domains our tools use
      relevant_domains = %w[light tts awtrix notify camera music_assistant script]
      relevant_domains.each do |domain|
        next unless services[domain]

        puts "\n#{domain.upcase} services:"
        services[domain].each do |service, info|
          puts "  • #{service}: #{info['description']&.truncate(60) || 'No description'}"
        end
      end
    rescue StandardError => e
      puts "❌ Connection failed: #{e.message}"
      puts 'Please check your HOME_ASSISTANT_URL and HOME_ASSISTANT_TOKEN configuration.'
    end
  end

  def analyze_tool_class(tool_class)
    class_name = tool_class.name.split('::').last
    puts "🔧 Analyzing #{class_name}"
    puts '-' * 40

    return unless tool_class.respond_to?(:available_tools)

    tool_class.available_tools.each do |tool_method|
      analyze_tool_method(tool_class, tool_method)
    end
  end

  def analyze_tool_method(tool_class, tool_method)
    puts "  📋 Method: #{tool_method}"

    comparison = @validator.compare_tool_schema_to_ha(tool_class, tool_method)

    case comparison[:status]
    when :no_tool_schema
      puts '    ⚠️  No tool schema defined'
    when :compared
      comparison[:comparisons].each do |comp|
        analyze_comparison(comp, tool_method)
      end
    end
  end

  def analyze_comparison(comp, _tool_method)
    service_name = "#{comp[:domain]}.#{comp[:service]}"

    case comp[:status]
    when :ha_schema_unavailable
      puts "    ❓ HA service #{service_name} schema unavailable"
    when :compatible
      puts "    ✅ Compatible with #{service_name}"
      show_suggestions(comp[:suggestions]) if comp[:suggestions]&.any?
    when :mismatched
      puts "    ❌ Mismatched with #{service_name}"
      comp[:mismatches].each do |mismatch|
        puts "      • #{mismatch}"
      end
      show_suggestions(comp[:suggestions]) if comp[:suggestions]&.any?
      show_ha_schema_details(comp[:ha_schema], service_name)
    end
  end

  def show_suggestions(suggestions)
    suggestions.each do |suggestion|
      puts "      💡 #{suggestion}"
    end
  end

  def show_ha_schema_details(ha_schema, service_name)
    puts "    📝 #{service_name} expected fields:"

    fields = ha_schema[:fields] || {}
    fields.each do |field_name, field_info|
      required = field_info['required'] ? ' (required)' : ''
      description = field_info['description'] || 'No description'
      selector = field_info['selector'] || {}

      puts "      • #{field_name}#{required}: #{description.truncate(50)}"

      # Show selector details for better understanding
      next unless selector.any?

      selector_type = selector.keys.first
      puts "        Type: #{selector_type}"

      case selector_type
      when 'select'
        options = selector.dig(selector_type, 'options')
        puts "        Options: #{options.join(', ')}" if options
      when 'number'
        min_val = selector.dig(selector_type, 'min')
        max_val = selector.dig(selector_type, 'max')
        puts "        Range: #{min_val}..#{max_val}" if min_val || max_val
      end
    end
  end
end

# Command line interface
def main
  options = {}

  ARGV.each_with_index do |arg, i|
    case arg
    when '--check-ha'
      options[:check_ha] = true
    when '--tool'
      options[:tool] = ARGV[i + 1]
    when '--output', '-o'
      options[:output] = ARGV[i + 1]
    end
  end

  HASchemaSync.new.run(options)
rescue StandardError => e
  puts "💥 Error: #{e.message}"
  puts e.backtrace if ENV['DEBUG']
  exit 1
end

# String truncation helper
class String
  def truncate(length)
    self.length > length ? "#{self[0...length]}..." : self
  end
end

main if __FILE__ == $PROGRAM_NAME
