# Template Sensors: Last Interaction, Current Persona, Installation Health
- platform: template
  sensors:
    last_interaction_time:
      unique_id: "last_interaction_time"
      friendly_name: "Last Interaction Time"
      value_template: >
        {% set last = states('input_datetime.last_interaction') %}
        {% if last != 'unknown' and last != 'unavailable' %}
          {{ as_timestamp(last) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
        {% else %}
          Never
        {% endif %}
      icon_template: "mdi:clock-outline"

    current_persona:
      unique_id: "current_persona"
      friendly_name: "Current Persona"
      value_template: >
        {% set persona = states('input_text.current_persona') %}
        {{ persona if persona not in ['unknown', 'unavailable', ''] else 'Default' }}
      icon_template: "mdi:account-multiple"

    installation_health:
      unique_id: "installation_health"
      friendly_name: "Installation Health"
      value_template: >
        {% set app_health = states('sensor.glitch_cube_app_health') %}
        {% set internet = states('sensor.internet_connectivity') %}
        {% set temp = states('sensor.cube_cpu_thermal_0_temperature') | float(0) %}
        {% set offline_mode = states('input_boolean.offline_mode') %}
        {# 
          Health Logic:
            - critical if app offline
            - offline if internet disconnected & offline_mode on
            - degraded if internet disconnected
            - warning if temp > 158F
            - healthy otherwise
        #}
        {% if app_health == 'offline' %}
          critical
        {% elif internet == 'disconnected' and offline_mode == 'on' %}
          offline
        {% elif internet == 'disconnected' %}
          degraded
        {% elif temp is number and temp > 158 %}
          warning
        {% else %}
          healthy
        {% endif %}
      icon_template: >
        {% set health = states('sensor.installation_health') %}
        {% if health == 'critical' %}
          mdi:alert-circle
        {% elif health == 'offline' %}
          mdi:wifi-off
        {% elif health == 'degraded' %}
          mdi:alert
        {% elif health == 'warning' %}
          mdi:alert-outline
        {% else %}
          mdi:check-circle
        {% endif %}