name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: RSpec Tests (Ruby ${{ matrix.ruby-version }})
    
    # Ensure the job fails when tests fail
    continue-on-error: false
    
    strategy:
      matrix:
        ruby-version: ['3.3']
      # Ensure all matrix jobs fail if any fail
      fail-fast: true
    
    env:
      RACK_ENV: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    

    - name: Run RSpec tests
      run: |
        # Ensure we capture the exit code properly
        bundle exec rspec \
          --format progress \
          --format RspecJunitFormatter \
          --out tmp/rspec_results.xml \
          --format documentation || exit $?
      