name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: RSpec Tests (Ruby ${{ matrix.ruby-version }})
    
    # Ensure the job fails when tests fail
    continue-on-error: false
    
    strategy:
      matrix:
        ruby-version: ['3.3']
      # Ensure all matrix jobs fail if any fail
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: glitchcube
          POSTGRES_PASSWORD: glitchcube_test
          POSTGRES_DB: glitchcube_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      CI: true
      RACK_ENV: test
      MOCK_HOME_ASSISTANT: true
      DATABASE_URL: postgresql://glitchcube:glitchcube_test@localhost:5432/glitchcube_test
      REDIS_URL: redis://localhost:6379
      OPENROUTER_API_KEY: test-api-key
      HOME_ASSISTANT_TOKEN: test-ha-token

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Wait for PostgreSQL to be ready
      run: |
        # Install PostgreSQL client tools
        sudo apt-get update && sudo apt-get install -y postgresql-client
        # Wait for PostgreSQL to be ready
        for i in $(seq 1 10); do
          pg_isready -h localhost -p 5432 -U glitchcube && break
          echo "Waiting for PostgreSQL... ($i/10)"
          sleep 5
        done
        pg_isready -h localhost -p 5432 -U glitchcube || (echo "PostgreSQL not ready after multiple attempts." && exit 1)
      env:
        PGPASSWORD: glitchcube_test
    
    - name: Set up database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
        

    - name: Run RSpec tests
      run: |
        # Ensure we capture the exit code properly
        bundle exec rspec \
          --format progress \
          --format RspecJunitFormatter \
          --out tmp/rspec_results.xml \
          --format documentation || exit $?
      